### ISSUE TITLE
run base/samples faild

### ISSUE THREAD

**Issue by Pillar1989** [01org/intel-iot-services-orchestration-layer#5]
Hi,
    I want to know all the project how to work. so I run the samples, and learn the project. but It's failed.
pillar@server:~/intel-iot-services-orchestration-layer/base$ node samples/lock.js 
    1  base/lock  lock test
    2  base/lock  _lock test
    3  base/lock  lock test
    4  base/lock  locked test
    5  base/lock  lock test
    6  base/lock  locked test
    7  base/lock  lock test
    8  base/lock  locked test
    9  base/lock  lock test
   10  base/lock  locked test
~~~ 5 - Giveup
   11  base/lock  lock test2
   12  base/lock  _lock test2
   13  base/lock  lock test2
   14  base/lock  locked test2
   15  base/lock  lock test2
   16  base/lock  locked test2

> > > 1 - Lock
> > > test 2 --- 1
> > >    17  base/lock  lock release test2
> > >    18  base/lock  _lock test2
> > > ~~~ 4 - Giveup
> > > <<< 1 - Release
> > >    19  base/lock  lock release test
> > >    20  base/lock  _lock test
> > > 2 - Lock
> > > test 2 --- 2
> > >    21  base/lock  lock release test2
> > >    22  base/lock  _lock test2
> > > <<< 2 - Release
> > >    23  base/lock  lock release test
> > >    24  base/lock  _lock test
> > > 3 - Lock
> > > test 2 --- 3
> > >    25  base/lock  lock release test2
> > > <<< 3 - Release
> > >    26  base/lock  lock release test
> > > pillar@server:~/intel-iot-services-orchestration-layer/base$ ls
> > > index.js  lib  node_modules  package.json  samples  test
> > > pillar@server:~/intel-iot-services-orchestration-layer/base$ node samples/
> > > assemble.js  check.js     lock.js      log.js  
> > > pillar@server:~/intel-iot-services-orchestration-layer/base$ node samples/assemble.js 
> > > AAA:  123
> > > BBB:  888
> > > BBB:  1 [REF] AAA<567>
> > > inner 333
> > > 888
> > > 888
> > > BBB:  1 [REF] AAA<567>
> > > This is external
> > > pillar@server:~/intel-iot-services-orchestration-layer/base$ node samples/check.js 
> > >     1  category   << CHECK >> Failed
> > >                   >>> LOG >>>    at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/check.js:32:7)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/check.js:38:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >                       at Function.Module._load (module.js:314:12)
> > > pillar@server:~/intel-iot-services-orchestration-layer/base$ node samples/log.js 
> > >     1  category   _info_ {
> > >                     a: 1,
> > >                     b: <FUNCTION: anonymous>,
> > >                     c: [1, 2, {
> > >                       m: 1,
> > >                       n: "2"
> > >                     }]
> > >                   } test
> > >     2  category   _warn_ {
> > >                     a: 1,
> > >                     b: <FUNCTION: anonymous>,
> > >                     c: [1, 2, {
> > >                       m: 1,
> > >                       n: "2"
> > >                     }]
> > >                   } test
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:47:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:61:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >     3  category   _error_ {
> > >                     a: 1,
> > >                     b: <FUNCTION: anonymous>,
> > >                     c: [1, 2, {
> > >                       m: 1,
> > >                       n: "2"
> > >                     }]
> > >                   } test
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:48:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:61:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >     4  my_cat     _info_ 1 2 3
> > >     5  my_cat     _warn_ 1 2 3
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:51:7)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:61:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >     6  my_cat     _error_ 1 2 3
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:52:7)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:61:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >     7  my_cat     _exception_ Error: **ERROR**
> > >                       at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:55:11)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:61:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >                       at Function.Module._load (module.js:314:12)
> > >                       at Function.Module.runMain (module.js:447:10)
> > >                       at startup (node.js:139:18)
> > >                       at node.js:999:3 <><><>
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:57:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:61:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >     8  category   _error_ {
> > >                     a: 1,
> > >                     b: <FUNCTION: anonymous>,
> > >                     c: [1, 2, {
> > >                       m: 1,
> > >                       n: "2"
> > >                     }]
> > >                   } test
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:48:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:75:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >     9  my_cat     _info_ 1 2 3
> > >    10  my_cat     _error_ 1 2 3
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:52:7)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:75:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >    11  my_cat     _exception_ Error: **ERROR**
> > >                       at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:55:11)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:75:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >                       at Function.Module._load (module.js:314:12)
> > >                       at Function.Module.runMain (module.js:447:10)
> > >                       at startup (node.js:139:18)
> > >                       at node.js:999:3 <><><>
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:57:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:75:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >    12  category   _error_ {
> > >                     a: 1,
> > >                     b: <FUNCTION: anonymous>,
> > >                     c: [1, 2, {
> > >                       m: 1,
> > >                       n: "2"
> > >                     }]
> > >                   } test
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:48:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:81:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >    13  my_cat     _error_ 1 2 3
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:52:7)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:81:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >    14  my_cat     _exception_ Error: **ERROR**
> > >                       at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:55:11)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:81:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)
> > >                       at Function.Module._load (module.js:314:12)
> > >                       at Function.Module.runMain (module.js:447:10)
> > >                       at startup (node.js:139:18)
> > >                       at node.js:999:3 <><><>
> > >                   >>> LOG >>>    at g (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:57:9)
> > >                       at f (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:39:3)
> > >                       at Object.<anonymous> (/home/pillar/intel-iot-services-orchestration-layer/base/samples/log.js:81:1)
> > >                       at Module._compile (module.js:413:34)
> > >                       at Object.Module._extensions..js (module.js:422:10)
> > >                       at Module.load (module.js:357:32)

**Comment by jiangzidong** [comment]
@Pillar1989 it doesn't fail, and the error messages are exactly what we want. 

`samples/check.js` and `samples/log.js` will show _error_, and the _error_ is actually a kind of message type desired in `base/lib/log.js`. 

The files in the sample folder are not test cases, they are examples to help developer understand the usage of the base methods.

**Comment by Pillar1989** [comment]
Thank you, wonderful code!
